### ISSUE TITLE
StoryManager stopped work at all today

### ISSUE THREAD

**Issue by CigarsSmoker** [Videogamers0/StoryManager#25]
Can't find the log file.
Can't copy error listing.

**Comment by Videogamers0** [comment]
Story Downloader functionality is now fixed.
[Version 1.0.10 published](https://github.com/Videogamers0/StoryManager/releases/latest)

**Comment by Supastyles** [comment]
first error
https://i.imgur.com/ha6Gt4d.png

I was having the same issue today.  found this post which inspired me to install the new version.  Sadly once installed I was still having the same issues!

I found this (you can notice the version number updated.)

https://i.imgur.com/mRnEfiv.png

So I was about to write a post about my issues then...

However I had over looked this error

https://i.imgur.com/ejjmwfB.png

to which I updated Webview2 and success.

My problem is it would load the app and maybe for 1-2 seconds then vanish without any warning or notifications.  I hope this helps anyone who may find this looking for answers!

**Comment by Videogamers0** [comment]
Hmm that's strange. Doesn't WebView2 automatically come with Windows 11 and Windows 10? I'm not sure why it wouldn't have been found on your computer. I'm assuming you never had StoryManager working until manually applying those WebView2 updates?

**Comment by Supastyles** [comment]
> Hmm that's strange. Doesn't WebView2 automatically come with Windows 11 and Windows 10? I'm not sure why it wouldn't have been found on your computer. I'm assuming you never had StoryManager working until manually applying those WebView2 updates?

I had it running before yes.  I hadn't ran it for awhile (2-3 months maybe) So I may have inadvertadly done something inbetween that time.  I think I did have it installed from what I could tell (I was trying to find what version I had unsuccessfully) so I just ran the update to make sure it was the most recent one and then it worked.  So Im not 100% if it installed it fully or just updated it.  (I just assumed it had updated it)
